"""
blockchain_client.py — Connects FastAPI backend to the private Hardhat network.

This replaces the Python smart_contract.py simulation with REAL on-chain calls.
Reads contract_info.json (generated by deploy.js) to get address + ABI.
"""

import json
import os
import logging
from pathlib import Path
from web3 import Web3
from web3.exceptions import ContractLogicError
from dotenv import load_dotenv
logger = logging.getLogger(__name__)

from pathlib import Path
load_dotenv(Path(__file__).parent / ".env")
# ── Config ────────────────────────────────────────────────────
HARDHAT_ENABLED  = os.getenv("HARDHAT_ENABLED", "false").lower() == "true"
HARDHAT_RPC_URL  = os.getenv("HARDHAT_RPC_URL", "http://127.0.0.1:8545")
DEPLOYER_KEY     = os.getenv("DEPLOYER_PRIVATE_KEY", "")
CONTRACT_ADDRESS = os.getenv("CONTRACT_ADDRESS", "")

# Path to contract_info.json generated by deploy.js
CONTRACT_INFO_PATH = Path(__file__).parent.parent / "blockchain" / "contract_info.json"


class BlockchainClient:
    def __init__(self):
        self.enabled  = HARDHAT_ENABLED
        self.w3       = None
        self.contract = None
        self.account  = None

        if self.enabled:
            self._connect()

    def _connect(self):
        try:
            self.w3 = Web3(Web3.HTTPProvider(HARDHAT_RPC_URL))

            if not self.w3.is_connected():
                logger.error("Cannot connect to Hardhat node at %s", HARDHAT_RPC_URL)
                logger.error("Make sure you ran: cd blockchain && npx hardhat node")
                self.enabled = False
                return

            if not CONTRACT_INFO_PATH.exists():
                logger.error("contract_info.json not found — run deploy.js first")
                self.enabled = False
                return

            with open(CONTRACT_INFO_PATH) as f:
                info = json.load(f)

            address = CONTRACT_ADDRESS or info["contract_address"]
            abi     = info["abi"]

            self.contract = self.w3.eth.contract(
                address=Web3.to_checksum_address(address),
                abi=abi,
            )

            if DEPLOYER_KEY:
                self.account = self.w3.eth.account.from_key(DEPLOYER_KEY)
            else:
                self.account = self.w3.eth.account.from_key(
                    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
                )

            logger.info("Connected to Hardhat node — contract at %s", address)
            logger.info("Owner wallet: %s", self.account.address)

        except Exception as e:
            logger.error("Blockchain connection failed: %s", e)
            self.enabled = False

    def _send_tx(self, fn):
        tx = fn.build_transaction({
            "from":     self.account.address,
            "nonce":    self.w3.eth.get_transaction_count(self.account.address, "pending"),
            "gas":      300000,
            "gasPrice": 1000000000,
        })
        signed  = self.w3.eth.account.sign_transaction(tx, self.account.key)
        tx_hash = self.w3.eth.send_raw_transaction(signed.raw_transaction)
        receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=25, poll_latency=0.1)
        return receipt

    def lock_funds(self, donation_id: str, donor_id: str, case_id: str) -> dict:
        if not self.enabled:
            return {"tx_hash": "mock_lock_" + donation_id, "block": 0, "on_chain": False}
        try:
            fn      = self.contract.functions.lockFunds(donation_id, donor_id, case_id)
            receipt = self._send_tx(fn)
            return {
                "tx_hash":  receipt.transactionHash.hex(),
                "block":    receipt.blockNumber,
                "on_chain": True,
                "status":   receipt.status,
            }
        except ContractLogicError as e:
            logger.error("lockFunds failed: %s", e)
            return {"tx_hash": None, "block": 0, "on_chain": False, "error": str(e)}

    def store_block_hash(self, block_index: int, block_hash: str, prev_hash: str, leader_node: str, donation_id: str) -> dict:
        if not self.enabled:
            return {"tx_hash": "mock_block_" + str(block_index), "block": block_index, "on_chain": False}
        try:
            bh = bytes.fromhex(block_hash)
            ph = bytes.fromhex(prev_hash) if prev_hash != "0" * 64 else bytes(32)
            fn      = self.contract.functions.storeBlockHash(block_index, bh, ph, leader_node, donation_id)
            receipt = self._send_tx(fn)
            return {
                "tx_hash":  receipt.transactionHash.hex(),
                "block":    receipt.blockNumber,
                "on_chain": True,
                "status":   receipt.status,
            }
        except ContractLogicError as e:
            logger.error("storeBlockHash failed: %s", e)
            return {"tx_hash": None, "block": 0, "on_chain": False, "error": str(e)}

    def release_milestone(self, donation_id: str, milestone: int) -> dict:
        if not self.enabled:
            return {"tx_hash": "mock_milestone_" + donation_id, "block": 0, "on_chain": False}
        try:
            fn      = self.contract.functions.releaseMilestone(donation_id, milestone)
            receipt = self._send_tx(fn)
            return {
                "tx_hash":  receipt.transactionHash.hex(),
                "block":    receipt.blockNumber,
                "on_chain": True,
                "status":   receipt.status,
            }
        except ContractLogicError as e:
            logger.error("releaseMilestone failed: %s", e)
            return {"tx_hash": None, "block": 0, "on_chain": False, "error": str(e)}

    def refund_escrow(self, donation_id: str, reason: str) -> dict:
        if not self.enabled:
            return {"tx_hash": "mock_refund_" + donation_id, "on_chain": False}
        try:
            fn      = self.contract.functions.refundEscrow(donation_id, reason)
            receipt = self._send_tx(fn)
            return {
                "tx_hash":  receipt.transactionHash.hex(),
                "block":    receipt.blockNumber,
                "on_chain": True,
                "status":   receipt.status,
            }
        except ContractLogicError as e:
            logger.error("refundEscrow failed: %s", e)
            return {"tx_hash": None, "on_chain": False, "error": str(e)}

    def verify_block_hash(self, block_index: int, block_hash: str) -> bool:
        if not self.enabled:
            return False
        try:
            bh = bytes.fromhex(block_hash)
            return self.contract.functions.verifyBlockHash(block_index, bh).call()
        except Exception:
            return False


# Singleton — import this everywhere
blockchain = BlockchainClient()